Algoritmo "Revisão 2"
//Refazendo Atv1 semana 2 em portugol

Var
   idade : inteiro
   salario : real
   sexo : caractere

Inicio

    escreva("Informe sua idade")
    leia(idade)
      
    escreva("Informe seu salário")
    leia(salario)
      
    escreva("Informe seu sexo")
    leia(sexo)
      
    escreva("Tenho ", idade, " anos, recebo R$", salario, " por mês e sou do sexo ", sexo)

Fimalgoritmo